apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-service
  namespace: poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-service
  template:
    metadata:
      labels:
        app: backend-service
    spec:
      containers:
        - name: backend-service
          image: ECR/backend-service:v1.0.3-beta.5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: poc
spec:
  selector:
    app: backend-service
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000